In [22]:
import pandas as pd

In [23]:
df = pd.read_csv("car data (1).csv")

In [24]:
df

,Car_Name,Year,Selling_Price,Present_Price,Driven_kms,Fuel_Type,Selling_type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0
...,...,...,...,...,...,...,...,...,...
296,city,2016,9.50,11.60,33988,Diesel,Dealer,Manual,0
297,brio,2015,4.00,5.90,60000,Petrol,Dealer,Manual,0
298,city,2009,3.35,11.00,87934,Petrol,Dealer,Manual,0
299,city,2017,11.50,12.50,9000,Diesel,Dealer,Manual,0
300,brio,2016,5.30,5.90,5464,Petrol,Dealer,Manual,0

In [25]:
df.isnull().sum()

Car_Name         0
Year             0
Selling_Price    0
Present_Price    0
Driven_kms       0
Fuel_Type        0
Selling_type     0
Transmission     0
Owner            0
dtype: int64

In [26]:
df.columns

Index(['Car_Name', 'Year', 'Selling_Price', 'Present_Price', 'Driven_kms',
       'Fuel_Type', 'Selling_type', 'Transmission', 'Owner'],
      dtype='object')

In [27]:
df[df.duplicated()]

,Car_Name,Year,Selling_Price,Present_Price,Driven_kms,Fuel_Type,Selling_type,Transmission,Owner
17,ertiga,2016,7.75,10.79,43000,Diesel,Dealer,Manual,0
93,fortuner,2015,23.00,30.61,40000,Diesel,Dealer,Automatic,0

In [28]:
df=df.drop_duplicates()

In [29]:
df.head()

,Car_Name,Year,Selling_Price,Present_Price,Driven_kms,Fuel_Type,Selling_type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0

In [30]:
df.tail()

,Car_Name,Year,Selling_Price,Present_Price,Driven_kms,Fuel_Type,Selling_type,Transmission,Owner
296,city,2016,9.50,11.6,33988,Diesel,Dealer,Manual,0
297,brio,2015,4.00,5.9,60000,Petrol,Dealer,Manual,0
298,city,2009,3.35,11.0,87934,Petrol,Dealer,Manual,0
299,city,2017,11.50,12.5,9000,Diesel,Dealer,Manual,0
300,brio,2016,5.30,5.9,5464,Petrol,Dealer,Manual,0

In [31]:
df.describe()

              Year  Selling_Price  Present_Price     Driven_kms       Owner
count   299.000000     299.000000     299.000000     299.000000  299.000000
mean   2013.615385       4.589632       7.541037   36916.752508    0.043478
std       2.896868       4.984240       8.566332   39015.170352    0.248720
min    2003.000000       0.100000       0.320000     500.000000    0.000000
25%    2012.000000       0.850000       1.200000   15000.000000    0.000000
50%    2014.000000       3.510000       6.100000   32000.000000    0.000000
75%    2016.000000       6.000000       9.840000   48883.500000    0.000000
max    2018.000000      35.000000      92.600000  500000.000000    3.000000

In [32]:
df

,Car_Name,Year,Selling_Price,Present_Price,Driven_kms,Fuel_Type,Selling_type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0
...,...,...,...,...,...,...,...,...,...
296,city,2016,9.50,11.60,33988,Diesel,Dealer,Manual,0
297,brio,2015,4.00,5.90,60000,Petrol,Dealer,Manual,0
298,city,2009,3.35,11.00,87934,Petrol,Dealer,Manual,0
299,city,2017,11.50,12.50,9000,Diesel,Dealer,Manual,0
300,brio,2016,5.30,5.90,5464,Petrol,Dealer,Manual,0

In [33]:
df["Car_Age"] = 2026 - df["Year"]

C:\Users\HP WORLD\AppData\Local\Temp\ipykernel_9448\3971151583.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Car_Age"] = 2026 - df["Year"]

In [34]:
df

,Car_Name,Year,Selling_Price,Present_Price,Driven_kms,Fuel_Type,Selling_type,Transmission,Owner,Car_Age
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0,12
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0,13
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0,9
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0,15
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0,12
...,...,...,...,...,...,...,...,...,...,...
296,city,2016,9.50,11.60,33988,Diesel,Dealer,Manual,0,10
297,brio,2015,4.00,5.90,60000,Petrol,Dealer,Manual,0,11
298,city,2009,3.35,11.00,87934,Petrol,Dealer,Manual,0,17
299,city,2017,11.50,12.50,9000,Diesel,Dealer,Manual,0,9
300,brio,2016,5.30,5.90,5464,Petrol,Dealer,Manual,0,10

In [35]:
df["Fuel_Type"] = df["Fuel_Type"].map({"Petrol" : 0 , "Diesel": 1, "CNG" : 3})
df["Transmission"] = df["Transmission"].map({"Manual" : 1, "Automatic" : 2})

C:\Users\HP WORLD\AppData\Local\Temp\ipykernel_9448\3379689595.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Fuel_Type"] = df["Fuel_Type"].map({"Petrol" : 0 , "Diesel": 1, "CNG" : 3})
C:\Users\HP WORLD\AppData\Local\Temp\ipykernel_9448\3379689595.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Transmission"] = df["Transmission"].map({"Manual" : 1, "Automatic" : 2})

In [53]:
df

,Car_Name,Year,Selling_Price,Present_Price,Driven_kms,Fuel_Type,Selling_type,Transmission,Owner,Car_Age
0,ritz,2014,3.35,5.59,27000,0,Dealer,1,0,12
1,sx4,2013,4.75,9.54,43000,1,Dealer,1,0,13
2,ciaz,2017,7.25,9.85,6900,0,Dealer,1,0,9
3,wagon r,2011,2.85,4.15,5200,0,Dealer,1,0,15
4,swift,2014,4.60,6.87,42450,1,Dealer,1,0,12
...,...,...,...,...,...,...,...,...,...,...
296,city,2016,9.50,11.60,33988,1,Dealer,1,0,10
297,brio,2015,4.00,5.90,60000,0,Dealer,1,0,11
298,city,2009,3.35,11.00,87934,0,Dealer,1,0,17
299,city,2017,11.50,12.50,9000,1,Dealer,1,0,9
300,brio,2016,5.30,5.90,5464,0,Dealer,1,0,10

In [54]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score

In [55]:
X = df[["Car_Age","Present_Price","Driven_kms", "Fuel_Type","Transmission"]]
y= df["Selling_Price"]

In [56]:
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size = 0.2 , random_state = 42)

In [57]:
model = LinearRegression()

In [58]:
model.fit(X_train, y_train)

LinearRegression()

In [59]:
accuracy = model.score(X_test, y_test)
accuracy

0.7500649059862722

In [67]:
def Predict_price():
    Car_Age = float(input("Enter the age of the car (years)= "))
    Present_Price = float(input("What is the present price of the car in showroom (in Lakhs) = "))
    Driven_kms = float(input("Enter total kilometers driven (kms) = "))
    Fuel_Type = int(input("Enter the fuel type of the car ( Petrol = 0 , Diesel = 1, CNG = 2) = "))
    Transmission = int(input("Enter whether the car is automatic or manual ( Manual = 1 , Automatic = 2) = "))

    car = pd.DataFrame([[Car_Age, Present_Price, Driven_kms, Fuel_Type, Transmission]], columns=["Car_Age","Present_Price","Driven_kms","Fuel_Type","Transmission"],)
    predict_price = model.predict(car)[0]
    print(f"Price of car will be = {predict_price:.2f}Lakhs")
    
Predict_price()

Enter the age of the car (years)=  10
What is the present price of the car in showroom (in Lakhs) =  23
Enter total kilometers driven (kms) =  2000
Enter the fuel type of the car ( Petrol = 0 , Diesel = 1, CNG = 2) =  0
Enter whether the car is automatic or manual ( Manual = 1 , Automatic = 2) =  2

Price of car will be = 14.02Lakhs

In [68]:
import pickle
filename = 'car_price_model.pkl'
with open(filename, 'wb') as file:
    pickle.dump(model, file)